ekf_node:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    two_d_mode: true
    publish_tf: true
    publish_acceleration: true

    frequency: 50.0

    odom0: /husky_velocity_controller/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true, false, false]
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # Reference:
    # - https://docs.ros.org/en/melodic/api/robot_localization/html/state_estimation_nodes.html#dynamic-process-noise-covariance
    dynamic_process_noise_covariance: true